// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1G82pMrqa2JRiwhFuNW_DYEBYO-f6v98',
    appId: '1:531231308653:web:e2ec87f4ce8f5cffde7864',
    messagingSenderId: '531231308653',
    projectId: 'tal3a-app-f354d',
    authDomain: 'tal3a-app-f354d.firebaseapp.com',
    storageBucket: 'tal3a-app-f354d.firebasestorage.app',
    measurementId: 'G-YD9QKDKYKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3CkJeNkd7dxbkez17PZc1uML-GamsEa4',
    appId: '1:531231308653:android:f596c8d6898964f8de7864',
    messagingSenderId: '531231308653',
    projectId: 'tal3a-app-f354d',
    storageBucket: 'tal3a-app-f354d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs63o_N41XKTju4o2SdbwxZA6z9_U4dEM',
    appId: '1:531231308653:ios:6d4bb54a31420a92de7864',
    messagingSenderId: '531231308653',
    projectId: 'tal3a-app-f354d',
    storageBucket: 'tal3a-app-f354d.firebasestorage.app',
    iosClientId: '531231308653-s9bjvqa6es87lj66l6794k937ittv075.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs63o_N41XKTju4o2SdbwxZA6z9_U4dEM',
    appId: '1:531231308653:ios:6d4bb54a31420a92de7864',
    messagingSenderId: '531231308653',
    projectId: 'tal3a-app-f354d',
    storageBucket: 'tal3a-app-f354d.firebasestorage.app',
    iosClientId: '531231308653-s9bjvqa6es87lj66l6794k937ittv075.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1G82pMrqa2JRiwhFuNW_DYEBYO-f6v98',
    appId: '1:531231308653:web:b48f0187dafed891de7864',
    messagingSenderId: '531231308653',
    projectId: 'tal3a-app-f354d',
    authDomain: 'tal3a-app-f354d.firebaseapp.com',
    storageBucket: 'tal3a-app-f354d.firebasestorage.app',
    measurementId: 'G-XEM53XLQK2',
  );
}
